### ISSUE TITLE
cifar_test_list.txt is missing?

### ISSUE THREAD

**Issue by nerddd** [dualplus/LTNet#1]
Could you provide **cifar_test_list.txt** used in res20_cifar_test_org.prototxt?Thank you 
And the **imglist.txt** in eval_cifar.py

**Comment by dualplus** [comment]
> Could you provide **cifar_test_list.txt** used in res20_cifar_test_org.prototxt?Thank you
> And the **imglist.txt** in eval_cifar.py

Thanks for your interest in our work.
I have uploaded "cifar_test_list.txt". It is also the imglist.txt used in eval_cifar.py.

**Comment by nerddd** [comment]
Thank you. It's a great work.
